
name: Test Azure login

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@bbcc074a232a35d7283353c18aabf0de1d557775 # v2 Mar 3 2025
